In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env=gym.make("FrozenLake-v0")

In [0]:
action_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

In [0]:
rewards_all_episodes=[]

for episode in range(num_episodes):
  state=env.reset()
  done=False
  rewards_current_episode=0

  for step in range(max_steps_per_episode):

    exploration_rate_threshold=random.uniform(0,1)
    if exploration_rate_threshold > exploration_rate:
      action=np.argmax(q_table[state,:])
    else:
      action=env.action_space.sample()
    
    new_state,reward,done,info=env.step(action)
    q_table[state,action]=q_table[state,action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state,:]))

    state=new_state
    rewards_current_episode+=reward

    if done==True:
      break

  exploration_rate=min_exploration_rate + (max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

  rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("******Average reward per thousand episodes*******\n")
for r in rewards_per_thousand_episodes:
  print(count,": ",str(sum(r/1000)))
  count+=1000
print("\n\n******Q-table**********\n")
print(q_table)

******Average reward per thousand episodes*******

1000 :  0.05400000000000004
2000 :  0.20100000000000015
3000 :  0.3860000000000003
4000 :  0.5340000000000004
5000 :  0.6440000000000005
6000 :  0.6410000000000005
7000 :  0.6920000000000005
8000 :  0.6700000000000005
9000 :  0.6690000000000005
10000 :  0.6900000000000005


******Q-table**********

[[0.5513037  0.51921824 0.51700138 0.51564693]
 [0.37660235 0.38193238 0.23935726 0.50960993]
 [0.44123831 0.39802132 0.394967   0.48157422]
 [0.2992153  0.26687591 0.30114211 0.46149409]
 [0.58006644 0.35799475 0.35238846 0.33218835]
 [0.         0.         0.         0.        ]
 [0.46548735 0.04372697 0.2023895  0.20158196]
 [0.         0.         0.         0.        ]
 [0.42540742 0.51624054 0.40378378 0.6043243 ]
 [0.48327332 0.68947249 0.38773969 0.37363911]
 [0.67178714 0.40382734 0.36874006 0.34397949]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.40847067 0.60176246 0.78610659 0.5